lw_2.exe input_image.bmp out_image.bmp 1 1
lw_2.exe input_image.bmp out_image.bmp 2 1
lw_2.exe input_image.bmp out_image.bmp 3 1
lw_2.exe input_image.bmp out_image.bmp 4 1
lw_2.exe input_image.bmp out_image.bmp 5 1
lw_2.exe input_image.bmp out_image.bmp 6 1
lw_2.exe input_image.bmp out_image.bmp 7 1
lw_2.exe input_image.bmp out_image.bmp 8 1
lw_2.exe input_image.bmp out_image.bmp 9 1
lw_2.exe input_image.bmp out_image.bmp 10 1
lw_2.exe input_image.bmp out_image.bmp 11 1
lw_2.exe input_image.bmp out_image.bmp 12 1
lw_2.exe input_image.bmp out_image.bmp 13 1
lw_2.exe input_image.bmp out_image.bmp 14 1
lw_2.exe input_image.bmp out_image.bmp 15 1
lw_2.exe input_image.bmp out_image.bmp 16 1

lw_2.exe input_image.bmp out_image.bmp 1 2
lw_2.exe input_image.bmp out_image.bmp 2 2
lw_2.exe input_image.bmp out_image.bmp 3 2
lw_2.exe input_image.bmp out_image.bmp 4 2
lw_2.exe input_image.bmp out_image.bmp 5 2
lw_2.exe input_image.bmp out_image.bmp 6 2
lw_2.exe input_image.bmp out_image.bmp 7 2
lw_2.exe input_image.bmp out_image.bmp 8 2
lw_2.exe input_image.bmp out_image.bmp 9 2
lw_2.exe input_image.bmp out_image.bmp 10 2
lw_2.exe input_image.bmp out_image.bmp 11 2
lw_2.exe input_image.bmp out_image.bmp 12 2
lw_2.exe input_image.bmp out_image.bmp 13 2
lw_2.exe input_image.bmp out_image.bmp 14 2
lw_2.exe input_image.bmp out_image.bmp 15 2
lw_2.exe input_image.bmp out_image.bmp 16 2

lw_2.exe input_image.bmp out_image.bmp 1 3
lw_2.exe input_image.bmp out_image.bmp 2 3
lw_2.exe input_image.bmp out_image.bmp 3 3
lw_2.exe input_image.bmp out_image.bmp 4 3
lw_2.exe input_image.bmp out_image.bmp 5 3
lw_2.exe input_image.bmp out_image.bmp 6 3
lw_2.exe input_image.bmp out_image.bmp 7 3
lw_2.exe input_image.bmp out_image.bmp 8 3
lw_2.exe input_image.bmp out_image.bmp 9 3
lw_2.exe input_image.bmp out_image.bmp 10 3
lw_2.exe input_image.bmp out_image.bmp 11 3
lw_2.exe input_image.bmp out_image.bmp 12 3
lw_2.exe input_image.bmp out_image.bmp 13 3
lw_2.exe input_image.bmp out_image.bmp 14 3
lw_2.exe input_image.bmp out_image.bmp 15 3
lw_2.exe input_image.bmp out_image.bmp 16 3

lw_2.exe input_image.bmp out_image.bmp 1 4
lw_2.exe input_image.bmp out_image.bmp 2 4
lw_2.exe input_image.bmp out_image.bmp 3 4
lw_2.exe input_image.bmp out_image.bmp 4 4
lw_2.exe input_image.bmp out_image.bmp 5 4
lw_2.exe input_image.bmp out_image.bmp 6 4
lw_2.exe input_image.bmp out_image.bmp 7 4
lw_2.exe input_image.bmp out_image.bmp 8 4
lw_2.exe input_image.bmp out_image.bmp 9 4
lw_2.exe input_image.bmp out_image.bmp 10 4
lw_2.exe input_image.bmp out_image.bmp 11 4
lw_2.exe input_image.bmp out_image.bmp 12 4
lw_2.exe input_image.bmp out_image.bmp 13 4
lw_2.exe input_image.bmp out_image.bmp 14 4
lw_2.exe input_image.bmp out_image.bmp 15 4
lw_2.exe input_image.bmp out_image.bmp 16 4